# Generated by Django 6.1.1 on 2026-09-16 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_published', models.BooleanField(default=True, verbose_name="saytda ko'rsatilsin")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='slug (URL)')),
                ('title', models.CharField(max_length=200, verbose_name='nomi')),
                ('category', models.CharField(max_length=50, verbose_name='toifa')),
                ('date', models.DateField(verbose_name='sana')),
                ('start_time', models.TimeField(verbose_name='boshlanish vaqti')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='tugash vaqti')),
                ('location', models.CharField(max_length=255, verbose_name='manzil')),
                ('short_desc', models.CharField(max_length=300, verbose_name='qisqa tavsif')),
                ('description', models.TextField(verbose_name="to'liq tavsif")),
                ('theme', models.CharField(choices=[('blue', "Ko'k"), ('cyan', 'Moviy'), ('purple', 'Binafsha'), ('yellow', 'Sariq'), ('red', 'Qizil'), ('emerald', 'Zumrad')], default='blue', max_length=20, verbose_name='rang')),
                ('prizes', models.JSONField(blank=True, default=list, verbose_name='sovrinlar')),
                ('requirements', models.JSONField(blank=True, default=list, verbose_name='ishtirok shartlari')),
                ('organizer', models.CharField(max_length=200, verbose_name='tashkilotchi')),
                ('seats', models.PositiveIntegerField(verbose_name="o'rinlar soni")),
                ('status', models.CharField(choices=[('upcoming', 'Tez orada'), ('open', "Ro'yxatdan o'tish ochiq"), ('closed', "Ro'yxatdan o'tish yopilgan")], default='upcoming', max_length=20, verbose_name='holati')),
            ],
            options={
                'verbose_name': 'tadbir',
                'verbose_name_plural': 'tadbirlar',
                'ordering': ('date', 'start_time'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='vaqt')),
                ('activity', models.CharField(max_length=255, verbose_name='faoliyat')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='events.event', verbose_name='tadbir')),
            ],
            options={
                'verbose_name': 'dastur bandi',
                'verbose_name_plural': 'tadbir dasturi',
                'ordering': ('time', 'id'),
            },
        ),
    ]
