# Generated by Django 6.1.1 on 2026-09-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='theme',
            field=models.CharField(choices=[('blue', "Ko'k"), ('cyan', 'Moviy'), ('purple', 'Binafsha'), ('yellow', 'Sariq'), ('red', 'Qizil'), ('emerald', 'Zumrad'), ('orange', "To'q sariq")], default='blue', max_length=20, verbose_name='rang'),
        ),
    ]
