# Generated by Django 6.1.1 on 2026-09-16 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_alter_course_icon_alter_course_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_published', models.BooleanField(default=True, verbose_name="saytda ko'rsatilsin")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('student_name', models.CharField(max_length=100, verbose_name="o'quvchi ismi")),
                ('course_name', models.CharField(blank=True, help_text="Kurs tanlanmagan bo'lsa shu matn ko'rsatiladi", max_length=100, verbose_name='kurs nomi (matn)')),
                ('result', models.CharField(max_length=255, verbose_name='natija')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Instagram yoki boshqa havola', verbose_name='video havolasi')),
                ('thumbnail', models.ImageField(blank=True, upload_to='stories/', verbose_name='muqova rasmi')),
                ('theme', models.CharField(choices=[('blue', "Ko'k"), ('cyan', 'Moviy'), ('purple', 'Binafsha'), ('yellow', 'Sariq'), ('red', 'Qizil'), ('emerald', 'Zumrad'), ('orange', "To'q sariq")], default='blue', max_length=20, verbose_name='rang')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_stories', to='courses.course', verbose_name='kurs')),
            ],
            options={
                'verbose_name': 'video story',
                'verbose_name_plural': "o'quvchilar natijalari (video)",
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
    ]
