# Generated by Django 6.1.1 on 2026-09-16 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='slug (URL)')),
                ('title', models.CharField(max_length=200, verbose_name='sarlavha')),
                ('category', models.CharField(max_length=50, verbose_name='toifa')),
                ('excerpt', models.CharField(max_length=300, verbose_name='qisqa matn')),
                ('content', models.TextField(help_text="Paragraflar bo'sh qator bilan ajratiladi", verbose_name="to'liq matn")),
                ('cover', models.ImageField(blank=True, upload_to='news/', verbose_name='muqova rasmi')),
                ('is_published', models.BooleanField(default=True, verbose_name="saytda ko'rsatilsin")),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='chop etilgan vaqt')),
            ],
            options={
                'verbose_name': 'yangilik',
                'verbose_name_plural': 'yangiliklar',
                'ordering': ('-published_at',),
            },
        ),
    ]
