# Generated by Django 6.1.1 on 2026-09-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_published', models.BooleanField(default=True, verbose_name="saytda ko'rsatilsin")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('title', models.CharField(max_length=100, verbose_name='nomi')),
                ('description', models.TextField(verbose_name='tavsif')),
                ('icon', models.CharField(choices=[('smartphone', 'Smartphone (mobil)'), ('terminal', 'Terminal (dasturlash)'), ('layers', 'Layers (qatlamlar)'), ('cpu', 'Cpu (elektronika)'), ('box', 'Box (3D)'), ('briefcase', 'Briefcase (loyiha)'), ('rocket', 'Rocket (startap)'), ('zap', 'Zap (energiya)'), ('users', 'Users (jamoa)'), ('trophy', "Trophy (g'alaba)"), ('printer', 'Printer'), ('monitor', 'Monitor (kompyuter)'), ('hammer', 'Hammer (asboblar)')], default='cpu', max_length=30, verbose_name='ikonka')),
                ('theme', models.CharField(choices=[('blue', "Ko'k"), ('cyan', 'Moviy'), ('purple', 'Binafsha'), ('yellow', 'Sariq'), ('red', 'Qizil'), ('emerald', 'Zumrad'), ('orange', "To'q sariq")], default='blue', max_length=20, verbose_name='rang')),
                ('image', models.ImageField(blank=True, upload_to='equipment/', verbose_name='rasm')),
            ],
            options={
                'verbose_name': 'laboratoriya jihozi',
                'verbose_name_plural': 'laboratoriya jihozlari',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_published', models.BooleanField(default=True, verbose_name="saytda ko'rsatilsin")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('title', models.CharField(max_length=100, verbose_name='sarlavha')),
                ('description', models.TextField(verbose_name='tavsif')),
                ('icon', models.CharField(choices=[('smartphone', 'Smartphone (mobil)'), ('terminal', 'Terminal (dasturlash)'), ('layers', 'Layers (qatlamlar)'), ('cpu', 'Cpu (elektronika)'), ('box', 'Box (3D)'), ('briefcase', 'Briefcase (loyiha)'), ('rocket', 'Rocket (startap)'), ('zap', 'Zap (energiya)'), ('users', 'Users (jamoa)'), ('trophy', "Trophy (g'alaba)"), ('printer', 'Printer'), ('monitor', 'Monitor (kompyuter)'), ('hammer', 'Hammer (asboblar)')], default='zap', max_length=30, verbose_name='ikonka')),
                ('theme', models.CharField(choices=[('blue', "Ko'k"), ('cyan', 'Moviy'), ('purple', 'Binafsha'), ('yellow', 'Sariq'), ('red', 'Qizil'), ('emerald', 'Zumrad'), ('orange', "To'q sariq")], default='blue', max_length=20, verbose_name='rang')),
            ],
            options={
                'verbose_name': 'afzallik',
                'verbose_name_plural': 'afzalliklar (Nega aynan biz?)',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_published', models.BooleanField(default=True, verbose_name="saytda ko'rsatilsin")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('name', models.CharField(max_length=150, verbose_name='nomi')),
                ('logo', models.ImageField(blank=True, upload_to='partners/', verbose_name='logotip')),
                ('url', models.URLField(blank=True, verbose_name='sayt havolasi')),
            ],
            options={
                'verbose_name': 'hamkor',
                'verbose_name_plural': 'hamkorlar',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('phone', models.CharField(max_length=50, verbose_name='telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='elektron pochta')),
                ('address', models.CharField(max_length=255, verbose_name='manzil')),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='ish vaqti')),
                ('map_url', models.URLField(blank=True, verbose_name='xarita havolasi')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
            ],
            options={
                'verbose_name': 'sayt sozlamalari',
                'verbose_name_plural': 'sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_published', models.BooleanField(default=True, verbose_name="saytda ko'rsatilsin")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('value', models.PositiveIntegerField(verbose_name='qiymat')),
                ('suffix', models.CharField(blank=True, default='+', max_length=10, verbose_name="qo'shimcha belgi")),
                ('label', models.CharField(max_length=100, verbose_name='matn')),
            ],
            options={
                'verbose_name': 'statistika',
                'verbose_name_plural': 'statistika',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
    ]
