# Generated by Django 6.1.1 on 2026-09-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_published', models.BooleanField(default=True, verbose_name="saytda ko'rsatilsin")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('name', models.CharField(max_length=150, verbose_name='ism-familiya')),
                ('role', models.CharField(max_length=150, verbose_name='lavozimi')),
                ('photo', models.ImageField(blank=True, help_text='Vertikal (3:4) rasm tavsiya etiladi', upload_to='team/', verbose_name='rasm')),
                ('bio', models.CharField(blank=True, help_text="Kartaga kursor olib borilganda ko'rinadi", max_length=300, verbose_name='qisqacha')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
            ],
            options={
                'verbose_name': "jamoa a'zosi",
                'verbose_name_plural': 'jamoa',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
    ]
