# Generated by Django 6.1.1 on 2026-09-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text="Vertikalroq (3:4) yoki kvadrat rasm yaxshi ko'rinadi", upload_to='hero/', verbose_name='bosh sahifa rasmi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_video_url',
            field=models.URLField(blank=True, help_text="YouTube havolasi yoki to'g'ridan-to'g'ri .mp4 havolasi. Video bo'lsa rasm o'rniga u ko'rsatiladi", verbose_name='bosh sahifa videosi'),
        ),
    ]
