# Generated by Django 6.1.1 on 2026-09-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_sitesettings_hero_image_sitesettings_hero_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text="Kvadrat (1:1) PNG yoki SVG, fon shaffof bo'lsin. Kamida 200x200 px (saytda 40x40 px ko'rsatiladi — Retina ekranlar uchun kattarog'i kerak). Bo'sh qoldirilsa 'YT' harflari chiqadi.", upload_to='logo/', verbose_name='logotip'),
        ),
    ]
