# Generated by Django 6.1.1 on 2026-09-16 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('is_published', models.BooleanField(default=True, verbose_name="saytda ko'rsatilsin")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug (URL)')),
                ('title', models.CharField(max_length=150, verbose_name='nomi')),
                ('short_desc', models.CharField(max_length=300, verbose_name='qisqa tavsif')),
                ('description', models.TextField(verbose_name="to'liq tavsif")),
                ('icon', models.CharField(choices=[('smartphone', 'Smartphone'), ('terminal', 'Terminal'), ('layers', 'Layers'), ('cpu', 'Cpu'), ('box', 'Box')], default='terminal', max_length=30, verbose_name='ikonka')),
                ('theme', models.CharField(choices=[('blue', "Ko'k"), ('cyan', 'Moviy'), ('purple', 'Binafsha'), ('yellow', 'Sariq'), ('red', 'Qizil'), ('emerald', 'Zumrad')], default='blue', max_length=20, verbose_name='rang')),
                ('duration', models.CharField(max_length=50, verbose_name='davomiyligi')),
                ('level', models.CharField(max_length=100, verbose_name='daraja')),
                ('format', models.CharField(max_length=100, verbose_name='format')),
                ('price', models.CharField(max_length=50, verbose_name='narxi')),
                ('seats', models.PositiveIntegerField(verbose_name="o'rinlar soni")),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='texnologiyalar')),
                ('outcomes', models.JSONField(blank=True, default=list, verbose_name='kurs natijalari')),
            ],
            options={
                'verbose_name': 'kurs',
                'verbose_name_plural': 'kurslar',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurriculumItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=50, verbose_name='hafta')),
                ('topic', models.CharField(max_length=255, verbose_name='mavzu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='courses.course', verbose_name='kurs')),
            ],
            options={
                'verbose_name': "o'quv dasturi bandi",
                'verbose_name_plural': "o'quv dasturi",
                'ordering': ('order', 'id'),
            },
        ),
    ]
