# Generated by Django 6.1.1 on 2026-09-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=models.CharField(choices=[('smartphone', 'Smartphone (mobil)'), ('terminal', 'Terminal (dasturlash)'), ('layers', 'Layers (qatlamlar)'), ('cpu', 'Cpu (elektronika)'), ('box', 'Box (3D)'), ('briefcase', 'Briefcase (loyiha)'), ('rocket', 'Rocket (startap)'), ('zap', 'Zap (energiya)'), ('users', 'Users (jamoa)'), ('trophy', "Trophy (g'alaba)"), ('printer', 'Printer'), ('monitor', 'Monitor (kompyuter)'), ('hammer', 'Hammer (asboblar)')], default='terminal', max_length=30, verbose_name='ikonka'),
        ),
        migrations.AlterField(
            model_name='course',
            name='theme',
            field=models.CharField(choices=[('blue', "Ko'k"), ('cyan', 'Moviy'), ('purple', 'Binafsha'), ('yellow', 'Sariq'), ('red', 'Qizil'), ('emerald', 'Zumrad'), ('orange', "To'q sariq")], default='blue', max_length=20, verbose_name='rang'),
        ),
    ]
