# Generated by Django 6.1.1 on 2026-09-16 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_alter_course_icon_alter_course_theme'),
        ('events', '0002_alter_event_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('type', models.CharField(choices=[('contact', 'Umumiy xabar'), ('course', 'Kursga yozilish'), ('event', "Tadbirga ro'yxatdan o'tish")], default='contact', max_length=20, verbose_name='turi')),
                ('name', models.CharField(max_length=100, verbose_name='ism')),
                ('phone', models.CharField(max_length=30, verbose_name='telefon')),
                ('message', models.TextField(blank=True, verbose_name='xabar')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_progress', "Ko'rib chiqilmoqda"), ('done', 'Yakunlangan'), ('rejected', 'Rad etilgan')], default='new', max_length=20, verbose_name='holati')),
                ('admin_note', models.TextField(blank=True, verbose_name='admin izohi')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='courses.course', verbose_name='kurs')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='events.event', verbose_name='tadbir')),
            ],
            options={
                'verbose_name': 'murojaat',
                'verbose_name_plural': 'murojaatlar',
                'ordering': ('-created_at',),
            },
        ),
    ]
